export default {

  POSTS_RECEIVED: 'POSTS_RECEIVED',
  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  POST_RECEIVED: 'POST_RECEIVED',
  POST_DELETED: 'POST_DELETED',
  POST_CREATED: 'POST_CREATED',
  SEARCH_POSTS_RECEIVED:'SEARCH_POSTS_RECEIVED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  CURRENT_LOCATION_CHANGED:'CURRENT_LOCATION_CHANGED'

}
